### ISSUE TITLE
Proposiciones Felix

### ISSUE THREAD

**Issue by Felix-Angel** [SistemasTecTlaxiaco/actividad-7-proposiciones-l-gicas-Felix-Angel#1]
[PROPOSICIONES MATE DISCRETAS_FELIX ANGEL GARCIA GARCIA_1AS.pdf](https://github.com/SistemasTecTlaxiaco/actividad-7-proposiciones-l-gicas-Felix-Angel/files/13184726/PROPOSICIONES.MATE.DISCRETAS_FELIX.ANGEL.GARCIA.GARCIA_1AS.pdf)

**Comment by elisa1223** [comment]
Portada: 25%
Procedimiento: 25%
Figuras,ilustraciones y fotografias: 25%
Resultados y conclusiones: 25%

Calificación final: 20/20
Evaluado por el equipo de Elisa.

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
